### ISSUE TITLE
Please review

### ISSUE THREAD

**Issue by mpatel5** [mpatel5/Imageblur#1]
Please review

**Comment by mpatel5** [comment]
Please review

**Comment by kenmazaika** [comment]
Hi @mpatel5 -

If you're unsure if the coding challenges or self directed lessons are correct, I suggest you review them on your upcoming mentor sessions over a video chat.  If you run into problems or error messages on the self directed lessons, don't hesitate to ask questions in the forum!

Hope this helps!

Cheers,
Ken
